### ISSUE TITLE
在 json表单下,点击“浏览”没反应

### ISSUE THREAD

**Issue by augusl** [deatil/dcat-form-media#1]
![rerererere](https://cdn.jsdelivr.net/gh/augusl/oss@master/rerererere.png)
![rerere](https://cdn.jsdelivr.net/gh/augusl/oss@master/rerere.png)

**Comment by deatil** [comment]
这个是jq选择器没法很好的选择类里面包含有`[]`这样的dom，模态用的jq也没法选中，所以这种情况不推荐使用

**Comment by augusl** [comment]
👌
