### ISSUE TITLE
在弹窗创建和编辑问题

### ISSUE THREAD

**Issue by de-memory** [deatil/dcat-form-media#10]
操作
1、点击创建-》关闭创建。
2、点击编辑-》点击预览，模态框没有出现。
初步分析，id="LakeFormMediaModellink"，加载了两次

**Comment by deatil** [comment]
模态里的表单那种？

**Comment by de-memory** [comment]
@deatil 是的

**Comment by deatil** [comment]
> @deatil 是的

这个后面版本修复了
