### ISSUE TITLE
 我有两个问题。问题1 下面图1。图2 找不到方法     问题2   弹窗的层级会被覆盖 导致窗口无法显示  图3

### ISSUE THREAD

**Issue by linechengchen** [deatil/dcat-form-media#13]
![image](https://user-images.githubusercontent.com/25653824/157358379-fcbbc1fc-1356-413c-ab49-565aac9b3ae2.png)
php8 +dcat2     
![image](https://user-images.githubusercontent.com/25653824/157358588-c356377e-2c64-4e95-8e8f-c36d813b9f68.png)

![image](https://user-images.githubusercontent.com/25653824/157358957-6a2db60e-21fd-44fd-b4c9-af812306f2bf.png)

    public function style(): void
    {

        Admin::style(
            <<<'CSS'
        #LakeFormMediaModelimgs{
            z-index: 99999999!important;
        }
        CSS
        );
        parent::style(); // TODO: Change the autogenerated stub
    }
![image](https://user-images.githubusercontent.com/25653824/157358750-5e5a2d62-8e4c-4aa8-b3db-ac16cf83bdf7.png)

 这个图是我在外面增加 z-index
  如果不增加两个窗口顺序会相反。导致打不开图片预览窗口

**Comment by deatil** [comment]
你的dcat-admin用的哪个版本，laravel版本是最新的v9吗？

**Comment by linechengchen** [comment]
<img width="1233" alt="截屏2022-03-09 上午11 01 05" src="https://user-images.githubusercontent.com/25653824/157364506-3126e8e2-53df-4b22-998b-2de238413bf2.png">
对的。 v9.1。

**Comment by deatil** [comment]
两个问题都修复了
