### ISSUE TITLE
如何集成裁切或resize呢?

### ISSUE THREAD

**Issue by chino7913** [deatil/dcat-form-media#14]
原來dcat 的上傳圖片 $form->image('pic')->resize(400, 300)方法有支援Intervention image圖片套件
用你這個$form->photo('pic')就無法支援 是否能加入這個 謝謝

**Comment by deatil** [comment]
加了resize裁剪方法，可以拉取新的试下

**Comment by chino7913** [comment]
> 

另外發現 上傳文件後都跳回首頁 
不會停留在原本的文件夾

**Comment by deatil** [comment]
> > 
> 
> 另外發現 上傳文件後都跳回首頁 不會停留在原本的文件夾

有设置文件夹的话是回到设置的文件夹吗

**Comment by chino7913** [comment]
這樣使用嗎 好像無效
`            $form->photo('pic','圖片')
                ->path('images/news')
                ->nametype('datetime')
                ->resize(400, 300)
                ->remove(true)
                ->help('單圖，可刪除')
                ->required();
`

另外是否有支持intervention/image原來的參數 
例如下面這樣
謝謝
`
->resize(400, 300, function ($constraint) {
     $constraint->aspectRatio();//等比例縮小
     $constraint->upsize();//如果太小保持原圖
})
`

**Comment by chino7913** [comment]
> > > 
> > 
> > 
> > 另外發現 上傳文件後都跳回首頁 不會停留在原本的文件夾
> 
> 有设置文件夹的话是回到设置的文件夹吗

剛剛更新後好像沒這個問題 我在試試看
謝謝

**Comment by deatil** [comment]
> 這樣使用嗎 好像無效 ` $form->photo('pic','圖片') ->path('images/news') ->nametype('datetime') ->resize(400, 300) ->remove(true) ->help('單圖，可刪除') ->required();`
> 
> 另外是否有支持intervention/image原來的參數 例如下面這樣 謝謝 `->resize(400, 300, function ($constraint) { $constraint->aspectRatio();//等比例縮小 $constraint->upsize();//如果太小保持原圖 })`

需要更新一次，浏览器的话需要强制刷新一次，把js更新到

**Comment by deatil** [comment]
像intervention默认那样估计不行

**Comment by deatil** [comment]
忘了，有个文件没更新过来，需要等我更新后再更新一次

**Comment by deatil** [comment]
没更新的文件更新了

**Comment by chino7913** [comment]
> 没更新的文件更新了

感謝您 剛測試是有裁切效果

如果之後還要升級的話可以考慮使用情境
您目前的做法是上傳到圖片庫時做裁切 欄位選擇圖片之後用選擇的圖片路徑保存在db
建議支持另一種是欄位上在圖片庫選擇圖片之後 ,按送出才做裁切並保存到指定參數目錄
就是圖片庫只是做選擇和上傳圖片(當然上傳是可以選擇是否先做裁切避免文件太大)
在表單送出之後才做裁切處理,  並複製到指定文件夾

比如說這個圖片我想要保存到會員的upload/user/1 文件夾, 跟選擇的圖片不同文件夾
就會需要多一個保存路徑
如果表單送出後再做裁切就更完美了
謝謝

**Comment by deatil** [comment]
> > 没更新的文件更新了
> 
> 感謝您 剛測試是有裁切效果
> 
> 如果之後還要升級的話可以考慮使用情境 您目前的做法是上傳到圖片庫時做裁切 欄位選擇圖片之後用選擇的圖片路徑保存在db 建議支持另一種是欄位上在圖片庫選擇圖片之後 ,按送出才做裁切並保存到指定參數目錄 就是圖片庫只是做選擇和上傳圖片(當然上傳是可以選擇是否先做裁切避免文件太大) 在表單送出之後才做裁切處理, 並複製到指定文件夾
> 
> 比如說這個圖片我想要保存到會員的upload/user/1 文件夾, 跟選擇的圖片不同文件夾 就會需要多一個保存路徑 如果表單送出後再做裁切就更完美了 謝謝

本地文件的话问题不是太大，用的其他oss的话会有问题的，暂时没法以你想要的方式来
