### ISSUE TITLE
这个能保存全路径吗

### ISSUE THREAD

**Issue by williamqian** [deatil/dcat-form-media#15]

**Comment by deatil** [comment]
是哪种全路径？点击选中后保存全路径还是自己添加全路径的数据？

**Comment by williamqian** [comment]
类似dcat-admin的saveFullUrl，保存到数据库里的是全路径
```php
$form->image('icon')->saveFullUrl();
```

**Comment by deatil** [comment]
> 类似dcat-admin的saveFullUrl，保存到数据库里的是全路径
> 
> ```
> $form->image('icon')->saveFullUrl();
> ```

这种现在还没有

**Comment by deatil** [comment]
后面可以加上

**Comment by williamqian** [comment]
> 后面可以加上

ok

**Comment by deatil** [comment]
可以更新到最新版试下

**Comment by williamqian** [comment]
> 可以更新到最新版试下

收到
