### ISSUE TITLE
模态窗(Modal)沒有作用

### ISSUE THREAD

**Issue by jay0324** [deatil/dcat-form-media#16]
![image](https://github.com/deatil/dcat-form-media/assets/6995608/5ceb5c5d-73b0-4226-9220-cca0a0fc87fd)
請問這個可以用在模态窗(Modal) (Dcat\Admin\Widgets\Form) 嗎? 

我在 Dcat\Admin\Form 中使用是可以用的，如下方是可以使用的代碼
protected function form()
    {
        return Form::make(new ProductSku(), function (Form $form) {
            $form->photo('thumb');
            $form->photos('sku_gallery', '圖片集')->nametype('original');
       });
     }

但如果在Dcat\Admin\Widgets\Form下是沒有作用的，是要引入什麼其他的東西嗎?
    public function form()
    {
        $this->photo('thumb', '列表圖');
        $this->photos('sku_gallery', '圖片集')->nametype('original');
    }

**Comment by deatil** [comment]
弹出的模态框测试好像是能用的。你先在浏览器的控制台看下模态的时候有没有报错提示
