### ISSUE TITLE
如图，图标错误

### ISSUE THREAD

**Issue by zwping** [deatil/dcat-form-media#19]
选择弹窗中 mp3的图标错误
<img width="429" alt="image" src="https://github.com/deatil/dcat-form-media/assets/26704739/1846cf12-65a6-4078-a890-d193c6fcb94b">

**Comment by zwping** [comment]
选择成功后的xlsx错误
<img width="465" alt="image" src="https://github.com/deatil/dcat-form-media/assets/26704739/e1fce8c1-626e-484c-91a0-10a8840f3c65">

**Comment by deatil** [comment]
感谢反馈。
新版本修复了这个问题
