### ISSUE TITLE
图片或视频的地址如果不是本地地址就没法显示

### ISSUE THREAD

**Issue by LISONGDASHUAIGE** [deatil/dcat-form-media#2]
前面会自动带上storage的路径

**Comment by deatil** [comment]
是上传到远程的服务器的吗？错误的有截图吗

**Comment by LISONGDASHUAIGE** [comment]
> 是上传到远程的服务器的吗？错误的有截图吗

我是直接在数据库改的视频连接，改成类似http://xx的外部地址的

**Comment by deatil** [comment]
> > 是上传到远程的服务器的吗？错误的有截图吗
> 
> 我是直接在数据库改的视频连接，改成类似[http://xx的外部地址的](http://xx%E7%9A%84%E5%A4%96%E9%83%A8%E5%9C%B0%E5%9D%80%E7%9A%84)

新版已经适配了这种情况了

**Comment by LISONGDASHUAIGE** [comment]
> > > 是上传到远程的服务器的吗？错误的有截图吗
> > 
> > 
> > 我是直接在数据库改的视频连接，改成类似[http://xx的外部地址的](http://xx%E7%9A%84%E5%A4%96%E9%83%A8%E5%9C%B0%E5%9D%80%E7%9A%84)
> 
> 新版已经适配了这种情况了

![image](https://user-images.githubusercontent.com/24515158/103599110-4e4af000-4f3f-11eb-82e3-40cc48013ad8.png)
好像还是没用。已经更新到1.0.8了

**Comment by deatil** [comment]
> ![image](https://user-images.githubusercontent.com/24515158/103599110-4e4af000-4f3f-11eb-82e3-40cc48013ad8.png)
> 好像还是没用。已经更新到1.0.8了

看起来像js缓存问题，你强制刷新下页面

**Comment by deatil** [comment]
后台扩展那也需要点击更新到最新

**Comment by LISONGDASHUAIGE** [comment]
> 后台扩展那也需要点击更新到最新

可以了，谢谢老哥
