### ISSUE TITLE
点击浏览，无法点击文件夹和图片

### ISSUE THREAD

**Issue by bfsz** [deatil/dcat-form-media#3]
您好。点击浏览，第一次无法点击文件夹和图片，需要刷新后才能点击，请问是怎么回事啊？

**Comment by deatil** [comment]
测试没有复现这个问题，你看下不能点击时js有没有报错的

**Comment by bfsz** [comment]
> 测试没有复现这个问题，你看下不能点击时js有没有报错的

版本 ：Dcat Admin  ·  v2.0.15-beta，js无任何报错。必须刷新页面后再点击浏览才能选择图片或视频。

**Comment by deatil** [comment]
> > 测试没有复现这个问题，你看下不能点击时js有没有报错的
> 
> 版本 ：Dcat Admin · v2.0.15-beta，js无任何报错。必须刷新页面后再点击浏览才能选择图片或视频。

刷新后，以后再点击还会出现这个问题吗？

**Comment by bfsz** [comment]
> > > 测试没有复现这个问题，你看下不能点击时js有没有报错的
> > 
> > 
> > 版本 ：Dcat Admin · v2.0.15-beta，js无任何报错。必须刷新页面后再点击浏览才能选择图片或视频。
> 
> 刷新后，以后再点击还会出现这个问题吗？

刷新后就不会出现这个问题。

**Comment by deatil** [comment]
> 刷新后就不会出现这个问题。

后面用不会再出现不能点击的问题了吧？
